### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by arsenvlad** [radhikakarthik/DM_Cluster_MarketPlace#1]
* Reformat JSON files so that it is easier to compare later (e.g. formated hard to read https://github.com/radhikakarthik/DM_Cluster_MarketPlace/blob/142cb380377446e879b4639d1ddc08bc34dc37e6/createUiDefinition.json#L44)

* Validate JSON files

**Comment by radhikakarthik** [comment]
Hi Arsen,

Do you recommend any tool/editor to format the JSON files? I have been using "Visual Studio Code" for formatting and template development. 

To validate the JSON files, I use Azure Resource Visualizer(http://old.armviz.io/#/).
What do you mean by "Validate JSON files"? I assume all files are valid one's.

Thanks,
Radhika
