### ISSUE TITLE
NTP servers

### ISSUE THREAD

**Issue by arsenvlad** [radhikakarthik/DM_Cluster_MarketPlace#2]
Will the deployment fail if user changes the NTP servers and provides "junk values"? There is no validation on these values and we need to make sure that the deployment does not fail if invalid or improperly formatted values are used here.

https://github.com/radhikakarthik/DM_Cluster_MarketPlace/blob/142cb380377446e879b4639d1ddc08bc34dc37e6/createUiDefinition.json#L200

**Comment by radhikakarthik** [comment]
No, the deployment will not fail if the user enters "junk values". But still I will make sure to add necessary validation there.
