### ISSUE TITLE
Disk Caching

### ISSUE THREAD

**Issue by arsenvlad** [radhikakarthik/DM_Cluster_MarketPlace#4]
This variable is not used: https://github.com/radhikakarthik/DM_Cluster_MarketPlace/blob/142cb380377446e879b4639d1ddc08bc34dc37e6/datamoverM-Yes.json#L247

Please discuss with Prabhu, but for database we had to go to Disk Caching = "ReadOnly" (which is the default) to minimize chance of issues.

Are the data disks for DataMover used mostly for read or write?

**Comment by radhikakarthik** [comment]
I have removed the unused variable from datamoverM-Yes.json and datamoverMA-Yes.json. 

Data Mover does both read and write equally. So I have specified caching as readwrite like below

"caching": "ReadWrite",

https://github.com/radhikakarthik/DM_Cluster_MarketPlace/blob/142cb380377446e879b4639d1ddc08bc34dc37e6/datamoverM-Yes.json#L595

https://github.com/radhikakarthik/DM_Cluster_MarketPlace/blob/142cb380377446e879b4639d1ddc08bc34dc37e6/datamoverMA-Yes.json#L601

**Comment by arsenvlad** [comment]
ReadWrite caching can NOT be used for any data disks as it can cause corruption. It is only recommended for the OS disk in Azure unless application uses flushes IOs, etc. Using ReadOnly is the appropriate setting for data disks if cache hit ratio is likely to be high.

**Comment by arsenvlad** [comment]
How heavy is the IO on the data disks of Data Mover? Is it same as database itself or much lighter usage? For OS disks it is OK to keep "ReadWrite". For the data disks, it looks like it is nothing specific - so means default of "None".

**Comment by radhikakarthik** [comment]
I am checking with our architects on this.

**Comment by radhikakarthik** [comment]
This issue is already addressed, so I am closing this.
