### ISSUE TITLE
Is aws_site.yml correct

### ISSUE THREAD

**Issue by arsenvlad** [radhikakarthik/DM_Cluster_MarketPlace#5]
This is most likely OK, but wanted to double-check with you whether it is "aws_site.yml" is the right file name here:

https://github.com/radhikakarthik/DM_Cluster_MarketPlace/blob/142cb380377446e879b4639d1ddc08bc34dc37e6/eco_ansi.sh#L15

**Comment by radhikakarthik** [comment]
Yes, that is the correct file name. This file is generic to both AWS and Azure. I took a note of it and we will fix it in the next release.
