### ISSUE TITLE
Use apiVersions parameter instead of hardcoded 2016-05-01 value

### ISSUE THREAD

**Issue by arsenvlad** [radhikakarthik/DM_Cluster_MarketPlace#7]
This applies to all parts where you refer to the storage account URL. Prabhu's team changed this yesterday in their templates.

https://github.com/radhikakarthik/DM_Cluster_MarketPlace/blob/36d455c5791a87c627c6f42c47f6f49fa72610ef/datamoverM-Yes.json#L559

https://github.com/radhikakarthik/DM_Cluster_MarketPlace/blob/36d455c5791a87c627c6f42c47f6f49fa72610ef/datamoverM-Yes.json#L571

https://github.com/radhikakarthik/DM_Cluster_MarketPlace/blob/36d455c5791a87c627c6f42c47f6f49fa72610ef/datamoverM-Yes.json#L589

https://github.com/radhikakarthik/DM_Cluster_MarketPlace/blob/36d455c5791a87c627c6f42c47f6f49fa72610ef/datamoverM-Yes.json#L598

https://github.com/radhikakarthik/DM_Cluster_MarketPlace/blob/36d455c5791a87c627c6f42c47f6f49fa72610ef/datamoverMA-Yes.json#L272

https://github.com/radhikakarthik/DM_Cluster_MarketPlace/blob/36d455c5791a87c627c6f42c47f6f49fa72610ef/datamoverMA-Yes.json#L576

https://github.com/radhikakarthik/DM_Cluster_MarketPlace/blob/36d455c5791a87c627c6f42c47f6f49fa72610ef/datamoverMA-Yes.json#L585

https://github.com/radhikakarthik/DM_Cluster_MarketPlace/blob/36d455c5791a87c627c6f42c47f6f49fa72610ef/datamoverMA-Yes.json#L594

https://github.com/radhikakarthik/DM_Cluster_MarketPlace/blob/36d455c5791a87c627c6f42c47f6f49fa72610ef/datamoverMA-Yes.json#L603

https://github.com/radhikakarthik/DM_Cluster_MarketPlace/blob/36d455c5791a87c627c6f42c47f6f49fa72610ef/datamoverMA-Yes.json#L673

**Comment by radhikakarthik** [comment]
Hardcoded 2016-05-01 has been updated with apiVersions parameter.
