### ISSUE TITLE
Remove public IPs from the instances for security

### ISSUE THREAD

**Issue by arsenvlad** [radhikakarthik/DM_Cluster_MarketPlace#8]
Prabhu's team removed all public IPs by default from instances that get created to avoid any chance of security issues. Even though you are setting NSGs on the instances it maybe still safer to keep them without public IPs by default and having the end-customer add required public IPs as needed. They could also jump box into these VMs through other VMs.

Unless you expect people ALWAYS needing public IPs on these VMs.

https://github.com/radhikakarthik/DM_Cluster_MarketPlace/blob/36d455c5791a87c627c6f42c47f6f49fa72610ef/datamoverMA-Yes.json#L271 (and all references to this)

https://github.com/radhikakarthik/DM_Cluster_MarketPlace/blob/36d455c5791a87c627c6f42c47f6f49fa72610ef/datamoverMA-Yes.json#L272 (and all references to this)

**Comment by radhikakarthik** [comment]
Public IP's have been removed from datamoverMA-json and datamover-M.json.
